[package]
name = "re_web"
authors.workspace = true
description = "Utilities for interacting with Web APIs"
edition.workspace = true
homepage.workspace = true
include.workspace = true
license.workspace = true
publish = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
targets = ["wasm32-unknown-unknown"]

[package.metadata.cargo-shear]
ignored = ["getrandom"] # enables the wasm backend used by re_log_types/re_tuid

[target.'cfg(target_arch = "wasm32")'.dependencies]
async-trait.workspace = true
bytes.workspace = true
constant_time_eq.workspace = true
getrandom = { workspace = true, features = ["wasm_js"] }
js-sys.workspace = true
re_async.workspace = true
re_log_types.workspace = true
re_string_interner = { workspace = true, features = ["bounded_runtime_intern"] }
url.workspace = true
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
  "Blob",
  "DomException",
  "File",
  "FileSystemDirectoryHandle",
  "FileSystemFileHandle",
  "FileSystemGetDirectoryOptions",
  "FileSystemGetFileOptions",
  "FileSystemRemoveOptions",
  "FileSystemWritableFileStream",
  "History",
  "Location",
  "Navigator",
  "ReadableStream",
  "StorageManager",
  "Url",
  "UrlSearchParams",
  "Window",
  "WritableStream",
] }
zeroize.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
constant_time_eq.workspace = true
re_log_types.workspace = true
re_string_interner = { workspace = true, features = ["bounded_runtime_intern"] }
url.workspace = true
zeroize.workspace = true

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
re_tuid.workspace = true
wasm-bindgen-test.workspace = true
